### PR TITLE
DL-172: Provide a IDL definition for stream metadata and segment meta…

### PR DESCRIPTION
**Pull request by gerritsundaram**
https://issues.apache.org/jira/browse/DL-172

### CODE REVIEW

**Comment by sijie** [comment]
@gerritsundaram looks like a findbugs warming. you might consider excluding the generated code.

regarding whether using thrift or protobuf, can you raise a discussion email thread for that?

**Comment by gerritsundaram** [comment]
@sijie sorry my bad. exclude the generated files from findbugs

**Comment by gerritsundaram** [comment]
@sijie will start a discussion thread for the protobuf.

**Comment by sijie** [comment]
@gerritsundaram are you still working on this? If no, mind closing this PR?

**Comment by sijie** [comment]
@gerritsundaram closing this PR for now. If there is any more interests on this, please reopen the pull request.

**Pull request closed without merging**
