### PR TITLE
DL-23: update libthrift version in distributedlog-core (part 1)

### PR DESCRIPTION
**Pull request by jiazhai**
- update libthrift version to 0.9.x and remove scrooge (as the libthrift is only used for namespace metadata)
- add generated thrift files under gen-java dir
- move write proxy related protocol to distributedlog-service-protocol-thrift
- move thrift related rpc code to distributedlog-client-thrift

### CODE REVIEW

**Comment by sijie** [comment]
@jiazhai it would good that you can send out the second part of this change. I took a look at this change initially. the layout seems to be fine. I would like to see how will you change the server side and decide later on. /cc @leighst 

also, this change is touching quite bunch of files. it will definitely conflict with the repackaging change made by @khurrumnasimm . so we'd coordinate on merging them.

**Comment by sijie** [comment]
@leighst can you also take a look at this?

I think it might be a good direction to go down to have a write-protocol specific client or service. so it is easy to extend in future, like adding gRPC support and such.

**Comment by leighst** [comment]
looking at this now

**Comment by sijie** [comment]
mind closing this PR? if it is inactive.

**Comment by khurrumnasimm** [comment]
@jiazhai mind closing this PR, if it is not active?

**Comment by sijie** [comment]
@jiazhai I fixed the thrift dependency in #132 . do you mind closing this PR?

**Comment by sijie** [comment]
@jiazhai I think this has been fixed as part of #132 . let's close this one as well.

**Pull request closed without merging**
