### PR TITLE
Issue 166: Code cleanup for 0.5.0 release

### PR DESCRIPTION
**Pull request by sijie**
Descriptions of the changes in this PR:

- add InterfaceAudience and InterfaceStability for public API to inform people what changes would be expected for those interface.
- avoid using guava classes in public API since we will provide a shaded jar for distributedlog-core
- enable ImportOrder checkstyle rule in some modules
- move `org.apache.distributedlog.io` to `distributedlog-common` module
- rename `setReadyToFlush` to `flush` and rename `flushAndSync` to `commit` for the new API

### CODE REVIEW

**Comment by zhaijack** [comment]
Hi @sijie, Thanks for the work,  After add check-style, there is error report: 
```
[INFO] There are 8 errors reported by Checkstyle 6.19 with distributedlog/checkstyle.xml ruleset.
[ERROR] src/main/java/org/apache/bookkeeper/client/BookKeeperAccessor.java:[0] (javadoc) JavadocPackage: Missing package-info.java file.
[ERROR] src/main/java/org/apache/bookkeeper/client/BookKeeperAccessor.java:[23] (javadoc) JavadocStyle: First sentence should end with a period.
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[39] (javadoc) JavadocParagraph: Empty line should be followed by <p> tag on the next line.
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[44,25] (naming) ConstantName: Variable 'logger' should be in ALL_CAPS (if it is a constant) or be private (otherwise).
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[46] (javadoc) JavadocType: Missing a Javadoc comment.
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[82,12] (modifier) ModifierOrder: 'public' modifier out of order with the JLS suggestions.
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[105] (sizes) LineLength: Line is longer than 120 characters (found 130).
[ERROR] src/main/java/org/apache/bookkeeper/client/LedgerReader.java:[154] (sizes) LineLength: Line is longer than 120 characters (found 125).
```
Would you please help fix them here?

**Comment by sijie** [comment]
@zhaijack nice catch. I will fix them.

**Comment by sijie** [comment]
@zhaijack actually where did you find this error? I can't reproduce at my laptop.

**Comment by jiazhai** [comment]
@sijie Please refer to the CI output: https://builds.apache.org/job/distributedlog-precommit-pullrequest/147/console

**Comment by zhaijack** [comment]
@sijie , please refer to the Ci output: https://builds.apache.org/job/distributedlog-precommit-pullrequest/147/console

**Pull request closed without merging**
